{% set name = "cuda-gdb" %}
{% set version = "13.2.75" %}
{% set cuda_version = ".".join(version.split(".")[:2]) %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]

package:
  name: cuda-gdb
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/opensource/13.1.1/cuda_gdb_src-all-all-{{ version }}.tar.gz
  sha256: acf55b75251f9b32d8d30aaafe5ea329525d38a8c6480acc25606806e957c881

build:
  number: 1
  # gdb version bundled (14.1) does not support py>=3.13
  skip: true  # [osx or win or ppc64le or py>=313]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - bison
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cuda-nvcc_{{ target_platform }} {{ cuda_version }}.*
    - gnuconfig  # [unix]
    - make >=3.82
    - pkg-config
    - python                                 # [build_platform != target_platform]
  host:
    - cuda-version {{ cuda_version }}
    - gmp
    - libiconv
    - liblzma-devel
    - mpfr
    - ncurses
    - python
    - readline
    - texinfo
    - zlib
    - zstd
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - libiconv
    - liblzma-devel
    - ncurses
    - pygments
    - python
    - six
    - zlib
    - zstd
  run_constrained:
      # cuda-gdb is a fork of gdb
    - gdb <0.0a0

test:
  commands:
    - test -f $PREFIX/bin/cuda-gdb
    - test -f $PREFIX/bin/cuda-gdbserver
    - test ! -d $PREFIX/extras/Debugger
    - test -d $PREFIX/share/gdb/syscalls
    - test -d $PREFIX/share/gdb/system-gdbinit
    - cuda-gdb --version
    - cuda-gdbserver --version

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: CUDA-GDB is the NVIDIA tool for debugging CUDA applications
  description: |
    CUDA-GDB is the NVIDIA tool for debugging CUDA applications running on Linux.
    CUDA-GDB is an extension to the x86-64 port of GDB, the GNU Project debugger.
  doc_url: https://docs.nvidia.com/cuda/cuda-gdb/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - isuruf
  feedstock-name: cuda-gdb
