{% set name = "cuda-gdb" %}
{% set version = "13.0.85" %}
{% set cuda_version = "13.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_gdb/{{ platform }}/cuda_gdb-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: a6bf87dac5edb64eee36425f6f8a91676966c456c49a213da5b3158581a4432f  # [linux64]
  sha256: 48bfce61e6f86661ec12bb65dd97e1607799406de5ceafccba2212962568d40e  # [aarch64]

build:
  number: 1
  skip: true  # [osx or win or ppc64le]
  skip: true  # [py<38 or py>312]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
  host:
    - python

outputs:
  - name: cuda-gdb
    build:
      binary_relocation: false
    files:
      - bin/cuda-gdb
      # We remove the wrapper script and rename one of the below to cuda-gdb
      # - bin/cuda-gdb-minimal
      # - bin/cuda-gdb-python{{ PY_VER }}-tui
      - bin/cuda-gdbserver
      - targets/{{ target_name }}/include
      # - extras/Debugger  # moved to targets/{{ target_name }}
      # - share/gdb  # revends components from gdb package
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
        - gmp
        - ncurses
        - python
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - ncurses
        - python
        # https://docs.nvidia.com/cuda/cuda-gdb/index.html#release-notes
        # Check release notes for supported GDB
        - gdb >=14.2,<15.0
    test:
      requires:
        - patchelf                                                # [linux]
      files:
        - test-rpath.sh                                           # [linux]
      commands:
        - test -f $PREFIX/bin/cuda-gdb
        # We remove the wrapper script and rename one of the below to cuda-gdb
        # - test -f $PREFIX/bin/cuda-gdb-minimal
        # - test -f $PREFIX/bin/cuda-gdb-python{{ PY_VER }}-tui
        - test -f $PREFIX/bin/cuda-gdbserver
        - test -f $PREFIX/targets/{{ target_name }}/include/cudadebugger.h
        - test ! -d $PREFIX/extras/Debugger
        - test -d $PREFIX/share/gdb/syscalls
        - test -d $PREFIX/share/gdb/system-gdbinit
        - bash test-rpath.sh                                      # [linux]
        - cuda-gdb --version
        # - cuda-gdb-minimal --version
        - cuda-gdbserver --version
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      dev_url: https://github.com/NVIDIA/cuda-gdb
      license_file: LICENSE
      license: GPL-3.0-only
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA-GDB is the NVIDIA tool for debugging CUDA applications
      description: |
        CUDA-GDB is the NVIDIA tool for debugging CUDA applications running on Linux.
        CUDA-GDB is an extension to the x86-64 port of GDB, the GNU Project debugger.
      doc_url: https://docs.nvidia.com/cuda/cuda-gdb/index.html

  - name: cuda-gdb-src
    files:
      - extras/cuda-gdb-{{ version }}.src.tar.gz
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    test:
      commands:
        - test -f $PREFIX/extras/cuda-gdb-{{ version }}.src.tar.gz
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      dev_url: https://github.com/NVIDIA/cuda-gdb
      license_file: LICENSE
      license: GPL-3.0-only
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA-GDB is the NVIDIA tool for debugging CUDA applications
      description: |
        CUDA-GDB is the NVIDIA tool for debugging CUDA applications running on Linux.
        CUDA-GDB is an extension to the x86-64 port of GDB, the GNU Project debugger.
      doc_url: https://docs.nvidia.com/cuda/cuda-gdb/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  dev_url: https://github.com/NVIDIA/cuda-gdb
  license_file: LICENSE
  license: GPL-3.0-only
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA-GDB is the NVIDIA tool for debugging CUDA applications
  description: |
    CUDA-GDB is the NVIDIA tool for debugging CUDA applications running on Linux.
    CUDA-GDB is an extension to the x86-64 port of GDB, the GNU Project debugger.
  doc_url: https://docs.nvidia.com/cuda/cuda-gdb/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: cuda-gdb
